server:
  port: 8000
spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    initialization-mode: always
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: false